[0;1;31m‚óè[0m gunicorn.service - gunicorn daemon
     Loaded: loaded (/etc/systemd/system/gunicorn.service; disabled; vendor preset: enabled)
     Active: [0;1;31mfailed[0m (Result: exit-code) since Mon 2021-01-11 14:57:00 UTC; 12s ago
TriggeredBy: [0;1;32m‚óè[0m gunicorn.socket
    Process: 39486 ExecStart=/home/team4/fdm-project/venv/bin/gunicorn --access-logfile - --workers 3 --bind unix:/run/gunicorn.sock myApp.wsgi:application [0;1;31m(code=exited, status=217/USER)[0m
   Main PID: 39486 (code=exited, status=217/USER)

Jan 11 14:57:00 ip-172-31-23-236 systemd[1]: Started gunicorn daemon.
Jan 11 14:57:00 ip-172-31-23-236 systemd[39486]: [0;1;31m[0;1;39m[0;1;31mgunicorn.service: Failed to determine user credentials: No such process[0m
Jan 11 14:57:00 ip-172-31-23-236 systemd[39486]: [0;1;31m[0;1;39m[0;1;31mgunicorn.service: Failed at step USER spawning /home/team4/fdm-project/venv/bin/gunicorn: No such process[0m
Jan 11 14:57:00 ip-172-31-23-236 systemd[1]: [0;1;39m[0;1;31m[0;1;39mgunicorn.service: Main process exited, code=exited, status=217/USER[0m
Jan 11 14:57:00 ip-172-31-23-236 systemd[1]: [0;1;38;5;185m[0;1;39m[0;1;38;5;185mgunicorn.service: Failed with result 'exit-code'.[0m
